cds-snc/dns

- cds-snc.ca/benefits-avantages.cds-snc.ca.tf
SSL isn't working yet on the new subdomain - this is because CNAME targets should use a different [herokudns.com domain](https://help.heroku.com/VKRNVVF5/what-is-the-correct-dns-cname-target-for-my-custom-domains). It's not browsable but in theory this should work.
> Updated dns target to get ssl working and corrected filename

- cds-snc.ca/redirect-apex.tf
The goal is to redirect traffic from cds-snc.ca to digital.canada.ca. The A record points to a static s3 site set up to redirect to digital.canada.ca: http://cds-redirect.s3-website.us-east-2.amazonaws.com
Not 100% sure this is going to work. Would it be better to try setting it up manually through the web interface first?
> Added an alias or A record

- cds-snc.ca/report-a-cybercrime.cds-snc.ca.tf
- cds-snc.ca/signalez-un-crime-informatique.cds-snc.ca.tf
This adds an A record for the report-a-cybercrime.cds-snc.ca.
The intent here is to have a domain we can use for setting up TLS config
as we work with getting our app running on Azure.
> Add a report-a-cybercrime subdomain for azure

- cds-snc.ca/report-a-cybercrime.cds-snc.ca.tf
- cds-snc.ca/signalez-un-crime-informatique.cds-snc.ca.tf
Apparently the static IP you can assign is associated with the
"nodeResourceGroup" which is specific to each cluster.
> Update Azure IPs again

- terraform/alpha.canada.ca-zone.tf
Route53 doesn't support cname records on apex domains. 
Interestingly enough, terraform plan didn't fail on this. :/
> [UPDATE] Swap out CNAME for A record alpha.canada.ca

- terraform/rescheduler.cds-snc.ca.tf
If your DNS record points to a distribution that is not the distribution that you are creating or modifying, then you can't add the alternate domain name to your distribution. In this scenario, you must update your DNS at your DNS provider before you can add the domain name for your CloudFront distribution.
https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/CNAMEs.html#alternate-domain-names-restrictions
the old one is already pointing to a distribution
> Breaking the rescheduler

- terraform/notification.alpha.canada.ca.tf
Added a secondary record for `notification.alpha.canada.ca` that will trigger if the healthcheck on the primary record fails
> Add in failover data

- README.md
- terraform/a11y.cds-snc.ca.tf
- terraform/alpha.canada.ca-zone.tf
- terraform/alpha.cds-snc.ca.tf
- terraform/benefits-avantages.cds-snc.ca.tf
- terraform/branch-review-apps.cds-snc.ca.tf
- terraform/cds-snc.ca.tf
- terraform/claim-tax-benefits.alpha.canada.ca.tf
- terraform/ebrief.cds-snc.ca.tf
- terraform/impact.cds-snc.ca.tf
- terraform/mailgun.cds-snc.ca.tf
- terraform/notification.alpha.canada.ca.tf
- terraform/nrcan-energuide-poc.cds-snc.ca.tf
- terraform/nrcanapi.cds-snc.ca.tf
- terraform/privacy-statements.alpha.canada.ca.tf
- terraform/report-a-cybercrime.cds-snc.ca.tf
- terraform/rescheduler-dev.cds-snc.ca.tf
- terraform/rescheduler.alpha.cds-snc.ca.tf
- terraform/rescheduler.cds-snc.ca.tf
- terraform/service-dashboard.cds-snc.ca.tf
- terraform/signalez-un-crime-informatique.cds-snc.ca.tf
- terraform/tell-us.cds-snc.ca.tf
- terraform/track-digital.cds-snc.ca.tf
- terraform/vac-benefits-finder.cds-snc.ca.tf
changed `zone_id = "${aws_route53_zone.cds-snc-ca-public.zone_id}"` to `zone_id = aws_route53_zone.cds-snc-ca-public.zone_id` to turn off the deprecation errors
> Changed format for tf 0.12.16 validation errors

- terraform/statcan.alpha.canada.ca.tf
> Rebasing with #75

- terraform/covid-benefits.alpha.canada.ca.tf
Adds English and French subdomains for the Covid-19 Benefits service.
The origin is an Azure CDN, proxying back to Azure App Service.
> Covid-19 Benefits subdomains

- README.md
Given our CI is effectively broken for outside collaborators, let's *not* encourage people to go that route.
Issues are good enough for now while we figure out what the next steps are for this service.
> Minor tweaks to content to avoid broken PR's

- terraform/covid-notification.alpha.canada.ca.tf
Delegated subdomain for covid-notification.alpha.canada.ca
> Covid notification

- terraform/covid-benefits.alpha.canada.ca.tf
This should be the last technical step before CDS has fully handed over the Benefit Finder. 
Please note that this is waiting on an ATO from the ESDC side before it can be merged, please do not merge until you recieve approval from DTS Delegated Authority.
This simply changes the CNAME from CDS' AppService to ESDC's AppService. 
After this is done a Custom Domain will have to be added to the AppService
Then we need to confirm that TLS/SSL Bindings have been configured:
> Handover of the COVID 19 Benefits Finder from CDS to ESDC

- terraform/covid-alert-portal.alpha.canada.ca.tf
Terraform file for covid-alert-portal.alpha.canada.ca
> DNS config for covid-alert-portal.alpha.canada.ca

- terraform/covid-alert-portal.alpha.canada.ca.tf
Switching the covid-portal production endpoints to the new Terraform deployment for COVID Alert Portal.
> Change endpoint to Terraform deployment for COVID Alert Portal

- .circleci/config.yml
- terraform/init.tf
This will pin the versions for the terraform image in the Circle CI configuration to `v0.12.29` and will pin the AWS provider version to `~> 2.70`. 
This should fix the issue we are currently having with the DNS TF not applying on merge to master.
> Pinning versions for Circle CI and AWS Provider

- terraform/covid-alert-portal.alpha.canada.ca.tf
Hopefully the last change.  Needed because of the way terraform bootstrapping and project require multi subdomains
> Covid alert portal - change in subdomain

- terraform/notification.alpha.canada.ca.tf
We swapped domain names `alpha.notification` VS `notification.alpha`
> fix: update ACM CNAME records for Notify alpha

- terraform/alpha.canada.ca-zone.tf
Adds a CNAME ACM validation for the new alpha.canada.ca home.
> feat: add new CNAME validation for alpha.canada.ca

- terraform/opencall-appelouvert-alpha-canada.ca.tf
Removes the old Cloudfront open call distribution
> fix: remove old open call CF distribution

- terraform/covid-alert-portal.alpha.canada.ca.tf
This PR removes the current CNAMES and Certificate validation entries and adds the Name Servers for the covid-alert-portal subdomain hosted in AWS.
> Change how traffic is routed to COVID Alert Portal

- terraform/notification.canada.ca-zone.tf
Some people think that the www part is required for URLs. Make sure that this DNS record exists and that it redirects
Related to https://github.com/cds-snc/notification-terraform/issues/117
> Set up www.notification.canada.ca

- terraform/id-alpha-canada-ca.tf
Adds `id.alpha.canada.ca` subdomain delegation to Azure name servers.
> feat: add id.alpha.canada.ca NS delegation

- terraform/notification.canada.ca-zone.tf
Verify the domain in `us-east-1` to receive inbound emails and adding an `MX` record to the root domain to delegate to SES.
> feat: set up SES inbound records for Notify

- terraform/covid-alert-portal.alpha.canada.ca.tf
Add new URLs for COVID Alert QR Code Registration site
> Add COVID Alert QR Code Registration site URLs

- terraform/list-manager.alpha.canada.ca.tf
This will provide subdomain delegation to the list-manager AWS account's hosted zone.
Related cds-snc/list-manager#31
Related cds-snc/list-manager#32
> feat: add list-manager.alpha.canada.ca NS record

- terraform/scan-websites.alpha.canada.ca.tf
This will provide subdomain delegation to the scan-websites AWS account's hosted zone.
Related cds-snc/scan-websites#117
Related cds-snc/scan-websites#118
> feat: add scan-websites.alpha.canada.ca NS record

- terraform/scan-files.alpha.canada.ca.tf
This will provide subdomain delegation to the scan-files AWS account's hosted zone.
Related cds-snc/scan-files#24
Related cds-snc/scan-files#25
> feat: scan-files subdomain delegation

- terraform/articles.alpha.canada.ca.tf
Subdomain delegation for articles.alpha.canada.ca
> Add subdomain delegation for articles.alpha.canada.ca

- terraform/tracker-alpha-canada-ca.tf
This PR adds a nameserver zone for `log4shell.tracker.alpha.canada.ca` as well as an A record to a nameserver for that subdomain. Any requests made to `log4shell.tracker.alpha.canada.ca` and any subdomains to that domain are now sent to the nameserver for resolution.
> feat: log4shell dns capture

- terraform/notification.canada.ca-zone.tf
We recreated the api-lambda custom domain names for the Notify api lambda api gateway.
We also added a domain name for api (in preparation for the canary test). Adding it here even though we don't need it yet.
Note that the domain `api-lambda.notification.canada.ca` is not used in production. It exists as a way for us to hit the api lambda for testing.
> add new api gateway domain name values

- terraform/notification.canada.ca-zone.tf
https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/266
Need to make this record weighted in preparation for the canary test. We also lower the ttl to make it easier to revert 😅 
**Note** ~that we will first modify the record using click ops and then do a terraform import. At this point, this PR should match the system and the plan / apply should be empty.~ I don't think we need to do this since the plan claims it'll change in place rather than being replaced.
> make Notify api record weighted

- terraform/notification.canada.ca-zone.tf
Add a weight zero record pointing api.notification.canada.ca to the api lambda function.
This is the last "getting ready for the canary" step. It should have no impact on production as the record is weight zero.
> add weight zero record for api lambda

- terraform/notification.canada.ca-zone.tf
This will route 5% of requests to the Notify API to the API Gateway
and Lambda infrastructure.  The remaining 95% will continue to
be served by the load balancer and Kubernetes API pods.
To rollback, reset the weights and re-deploy.  The 60 second
TTL on the records will ensure a short period of impacted users.
This PR also contains an unrelated TXT record change that had been 
added manually in the console.
* cds-snc/notification-planning#380
> feat: set Notify Lambda API DNS weight to 5%

- terraform/notification.canada.ca-zone.tf
API Gateway custom domain names must be type ALIAS.  The CNAME
we were using before may have been responsible for some user
requests attempting to use the wrong SSL certificate.
The `ttl` has been removed because ALIAS records have a TTL of
60 seconds that cannot be changed.
* cds-snc/notification-planning#437
> fix: Notify API weighted records should be ALIAS

- .tool-versions
- terraform/notification.canada.ca-zone.tf
Update the `api.notification.canada.ca` weighted records to have
the Lambda API serve 5% of traffic, while the Kubernetes API
pods handle the other 95%.
Also includes an [asdf](https://asdf-vm.com/) `.tool-versions` file to pin the Terraform
version for any local Terraform commands.
> feat: Notify Lambda API 5% traffic

- terraform/notification.canada.ca-zone.tf
The API Gateway custom domain name record should be an ALIAS
instead of CNAME.
* #226 
* cds-snc/notification-planning#437
> fix: `api-lambda.notification.canada.ca` should be ALIAS

- terraform/notification.canada.ca-zone.tf
Update the weighting on the Lambda API to handle ~10% of requests.
> feat: increase Notify Lambda API traffic to 10%

- terraform/url-shortener.alpha.canada.ca.tf
This will provide subdomain delegation to the url-shortener AWS account's hosted zone. 
The Draft PR with the infrastructure code for url-shortener can be found [here](https://github.com/cds-snc/url-shortener/pull/6).
> Url shortener subdomain delegation (url-shortener.alpha.canada.ca)

- terraform/notification.canada.ca-zone.tf
Update the `api.notification.canada.ca` DNS weight to have
75% Kubernetes, 25% Lambda.
> feat: set Notify Lambda API weight to 25%

- terraform/notification.canada.ca-zone.tf
Update the weighting of the Notify API DNS records so that
50% is Lambda API and 50% is Kubernetes.
> feat: set Lambda API to 50% traffic

- .github/workflows/terraform-apply.yml
Previous runs were failing because no `terraform init` was
run.  This also adds a `terraform plan` step as a final sanity
check.
We should expect to see the following PR's changes in the
Terraform plan as they were not applied successfully:
* #241
> fix: add terraform init/plan steps

- terraform/design.canada.ca.tf
Add TXT record to verify the ownership of domain with Netlify.
> Add TXT record to verify domain

- terraform/cds-snc.ca.tf
Create DKIM records to validate Freshdesk support emails
sent from the @cds-snc.ca domain.
* [Freshdesk: Email domain verification using DKIM records](https://support.freshdesk.com/en/support/solutions/articles/223779-digitally-sign-emails-with-dkim-)
* [Gmail help: Extra info next to sender’s name](https://support.google.com/mail/answer/1311182?hl=en#zippy=%2Ci-see-via-and-a-website-name-next-to-the-senders-name)
> feat: DKIM to verify Freshdesk support emails

- terraform/statcan.alpha.canada.ca.tf
Due to our lack of OIDC in DNS we have to follow this pattern (this will change in the future)
Closes: https://github.com/cds-snc/dns/pull/272
> feat: copy over from statcan pr

- terraform/notification.alpha.canada.ca.tf
GCNotify still get traffic hitting the API in kubernetes because many users still use the alpha API URL (i.e. api.notification.alpha.canada.ca). By redirecting the alpha API URL to the live production Route53 weighted record, all traffic should get through the lambda with current configuration.
1. Hit the api.notification.alpha.canada.ca URL and check logs to see if it hits the kubernetes cluster or the lambda.
> Redirect alpha API URL to live URL

- terraform/notification.alpha.canada.ca.tf
Target the api.notification.alpha.canada.ca to lambda API.
Send a notification to the API using `api.notification.alpha.canada.ca`.
> Target api alpha domain to lambda api

- terraform/notification.alpha.canada.ca.tf
Our trial failed again in production, so we are...
* Reverting DNS change to target alpha URL to lambda.
It would be much better if we could test this in staging.
> Reverting DNS change to target alpha URL to lambda

- terraform/resources.alpha.canada.ca.tf
Adds two new subdomains for Learning Resources
- `resources.alpha.canada.ca` - English
- `ressources.alpha.canada.ca` - French
🔗 [GH issue](https://github.com/cds-snc/resources-ressources/issues/289) on the Learning Resources repo
> feat: add learning resources subdomains (en and fr)

- bootstrap/init.tf
- terraform/init.tf
Update the Terraform AWS provider to the 3.x release.
Going through the upgrade notes from 2.x to 3.x, the only change thay could have impacted us was a difference in how the `aws_route53_zone` resource returns its `name` attribute.
In 3.x, it no longer includes a `.` suffix, but we do not make use of this attribute so there's no impact.
- **[Terraform 3.x upgrade guide](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/version-3-upgrade)**
- #307 
- cds-snc/platform-core-services#215
> chore: bump AWS provider to 3.x

- bootstrap/init.tf
- terraform/init.tf
Upgrade the Terraform AWS provider to the 4.x version.
There are no changes in the 3.x to 4.x upgrade guide that impact us.
- **[Terraform AWS 4.x upgrade guide](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/version-4-upgrade)**
- Closes cds-snc/platform-core-services#215
- Closes #307
> chore: bump AWS provider to 4.x

- terraform/github-secret-scanning.alpha.canada.ca.tf
Add nameserver records for the GitHub secret scanning service.
- cds-snc/site-reliability-engineering#812
- cds-snc/notification-planning#838
> feat: NS records for GitHub secret scanning service

- terraform/url-shortener.alpha.canada.ca.tf
Updates records to the new `o.alpha.canada.ca` hosted zone
> fix: update URL shortener NS records

- terraform/design-system.alpha.canada.ca.tf
Add the NS record required to subdomain delegate the `cdn.design-system.alpha.canada.ca` URL to the
Design System AWS account.
- cds-snc/platform-core-services#322
> feat: add Design System CDN subdomain delegation

- terraform/platform.canada.ca-zone.tf
Create a Route53 hosted zone `platform-plateforme.canada.ca`.
> feat: hosted zone for the Platform business unit

- terraform/notification.canada.ca-zone.tf
Adding the notify system status certificate validation record.
TF Apply works, nslookup on 
_7deec9582fbcae0f970d8192e402d455.status.notification.canada.ca
should return:
_460cff15b0106252f78a3e2257c44d80.mhbtsbpdnt.acm-validations.aws.
> feat: Adding system status static website dns validation CNAME

- terraform/notification.canada.ca-zone.tf
Disregard branch name - this is a CNAME, not an A record. 
Adding the notify system status CNAME to point to the new cloudfront distribution
nslookup status.notification.canada.ca should resolve to:
d2ica3mejnwxm3.cloudfront.net
> feat: Adding the notify status cloudfront CNAME

- terraform/statcan.alpha.canada.ca.tf
Remove the records for `statistics.alpha.canada.ca` and `statistique.alpha.canada.ca` as these are no longer needed.
This is duplicating @justbert's PR #362 as a way to make sure the Terraform plan runs as expected.
- Closes #362
> chore: remove unused StatsCan CNAMEs

- terraform/cds-snc.ca.tf
Registering Mailchimp with the CDS domain
> feat: add mailchimp dkim CNAME records

- terraform/inspection.alpha.canada.ca.tf
Add NS to delegate the `inspection.alpha.canada.ca` subdomain. This will be used by the CFIA AI Labratory team (#370)
- Closes #370
> feat: add inspection.alpha.canada.ca subdomain delegation

- terraform/statcan.alpha.canada.ca.tf
Adds the following 2 CNAME records:
- census.alpha.canada.ca
- recensement.alpha.canada.ca
- Closes https://github.com/cds-snc/dns/pull/377
> feat(dns): Add CNAME for census.alpha.canada.ca

- terraform/notification.canada.ca-zone.tf
The DKIM records for notification.canada.ca SES for us-east-1 were not here, and as such DKIM validation is failing in production.
TF Apply works 
Trigger DKIM validation on production notify SES
> chore: Adding DKIM records for us-east-1 notification-canada-ca

- terraform/notification.canada.ca-role.tf
Closes #395 
New IAM role that will allow the following:
1. List hosted zones, get hosted zones count and list hosted zone names permissions.
2. Change hosted zone records only for notification.canada.ca hosted zone.
3. Allow this role to be assumed by the github oidc role
> Adding a new iam role that will allow notify to manage notifcation.canada.ca domain

- terraform/github-user.tf
Adding UpdateAssumeRolePolicy permission to the github user so that we can update the assume role policy.
> Adding UpdateAssumeRolePolicy permission to the github user

- .github/workflows/terraform-apply.yml
- .github/workflows/terraform-plan.yml
- terraform/notification.canada.ca-role.tf
The terraform apply fails since it does not like wildcards. Upon further research, it seems you can't have wildcards in the principal so I put it in a secret variable.
> Making the SSO role secret for enhanced security

- terraform/notification.canada.ca-role.tf
Our Terraform is failing:
```
is not authorized to perform: route53:ListTagsForResource on resource: arn:aws:route53:::hostedzone/Z1XG153PQF3VV5 because no identity-based policy allows the route53:ListTagsForResource action
```
Adding in the required permissions
TF Plan works 🤞
> Adding list tags permissions for Notify IAM

- terraform/github-user.tf
TF Apply is failing due to missing permissions for the github user. 
TF Apply works
> Github User - Add List Policies

- terraform/notification.alpha.canada.ca.tf
- terraform/notification.canada.ca-role.tf
- terraform/notification.canada.ca-zone.tf
Removing references to notification.canada.ca as they are now done in notification-terraform
TF Apply shows no changes
> Remove notification canada ca

- terraform/gccloudone.alpha.canada.ca.tf
Adds the following CNAME records:
- gccloudone.alpha.canada.ca
- aurora.gccloudone.alpha.canada.ca
Closes [feat(dns): Add DNS domain for gccloudone alpha initiative](https://github.com/cds-snc/dns/pull/422)
> Adding gccloudone cname code

- .github/workflows/dangling-dns-record.yml
- bin/get-dns-records.sh
Add a scheduled workflow that will extract A, CNAME and NS records from the Terraform and check if any are vulnerable to takeover.
This use's the following action to perform the DNS checks:
https://github.com/maxneuvians/dns-hijack-check-action
If any dangling records are found, a Slack message will be posted to Internal SRE.
> feat: add dangling DNS record check

- terraform/dec.alpha.canada.ca.tf
Creates zone delegation for the Digital Earth Canada PoC being run by CSA/ECCC/NRCan, hosted in SSC Science Program's AWS tenant.
DEC is an effort to centrally provide environments for GoC scientists that use Earth Observartion (EO) data for their tasks. It will host AI/ML platforms, EO data (satellite, plane, drone, etc..) and other tools.
- Closes #427
> feat: Delegation for Digital Earth Canada (DEC)

- terraform/statcan.alpha.canada.ca.tf
Add CNAMEs to the StatsCan Flood Risk Portal.
- Closes #431
> feat: add CNAMEs for Flood Risk Portal

- terraform/superset.alpha.canada.ca.tf
Add NS records for the `superset.alpha.canada.ca` hosted zone. This will be used by the production instance of Superset.
- https://github.com/cds-snc/platform-core-services/issues/617
> feat: superset subdomain delegation

- terraform/superset.cds.snc.ca.tf
Add a new NS record so that we can move the production instance of Superset to the cds-snc.ca domain.
⚠️ Once the move is complete, I'll get a PR in to remove the `superset.alpha.canada.ca` NS record.
- https://github.com/cds-snc/platform-core-services/issues/617
> feat: add superset.cds-snc.ca subdomain delegation

- terraform/gccatalogue.alpha.canada.ca.tf
Update to a CNAME record so that the site can be hosted on GitHub pages.
Co-authored by: @nd-tbs
- Closes #457 
- Closes #455
> feat: update gccatalogue.alpha.canada.ca to CNAME

- terraform/ai-answers.alpha.canada.ca.tf
Closes #460 
Adding NS records for ai-answers.alpha.canada.ca
> NS records for ai-answers.alpha.canada.ca 

- terraform/innovation.alpha.canada.ca.tf
DNS record for innovation.alpha.canada.ca as referenced in this PR - https://github.com/cds-snc/dns/pull/462
> Adding innovation.alpha.canada.ca TF record

- terraform/issue-verify.alpha.canada.ca.tf
issue-verify.alpha.canada.ca and deliverance-verification.alpha.canada.ca have been created in Azure, and we need to create delegation for these so that DNS for the subdomain can be managed in Azure. These subdomains will be used for the upcoming partner-test and prod GC Issue and Verify environments.
We'll be testing the delegation after they're in place when we deploy our partner-test and prod environments.
> Delegate GC Issue and Verify alpha.canada.ca subdomains to Azure

- terraform/gciv-dvgc.alpha.canada.ca.tf
Delegation of gciv-dvgc.alpha.canada.ca to Azure DNS
The zone is managed in Azure and will be used primarily by the CDN instance for GC Issue & Verify
I will conduct some DNS lookups to test this after it's implemented.
> Delegation of gciv-dvgc.alpha.canada.ca to Azure DNS
