- cds-snc.ca/vac-benefits-finder.cds-snc.ca.tf
Just redirecting our vanity url to their new service
> update vac domain (moved to vac azure space)

- cds-snc.ca/find-benefits-and-services.cds-snc.ca.tf
Let me know if I did this right! I'd like the subdomain to be: find-benefits-and-services.cds-snc.ca, and I'd like it to mirror (point to? not sure the right term) this heroku app: https://find-benefits-and-services.herokuapp.com
> Added new subdomain for VAC repackaging work, points to heroku deployment

- cds-snc.ca/alpha.canada.ca-zone.tf
- cds-snc.ca/beta.canada.ca-zone.tf
- cds-snc.ca/cds-snc.ca-zone.tf
Exactly the same change @dsamojlenko made in fixing my other PR, just broken out into a separate one.
> Use updated syntax for tags

- cds-snc.ca/report-a-cybercrime.cds-snc.ca.tf
- cds-snc.ca/signalez-un-crime-informatique.cds-snc.ca.tf
This ip is now an azure [static IP](https://docs.microsoft.com/en-us/azure/aks/static-ip) so we don't have to keep changing it.
> Update report-a-cybercrime ips

- cds-snc.ca/report-a-cybercrime.cds-snc.ca.tf
- cds-snc.ca/signalez-un-crime-informatique.cds-snc.ca.tf
This is now a cluster in the RCMP Azure tenant.
> Point cybercrime domains at RCMP Azure.

- terraform/alpha.cds-snc.ca.tf
Temporary while waiting for alpha.canada.ca delegation to be resolved.
> [ADD] notification.alpha.cds-snc.ca

- terraform/notification.alpha.canada.ca.tf
Document API needs an endpoint too :(
> Added Document API endpoint

- terraform/cds-snc.ca.tf
This should fix that issue where two txt records kept cancelling each other out on all PRs.
> combine two conflicting txt records

- terraform/privacy-statements.alpha.canada.ca.tf
add a url for the privacy statement generator
> Add urls for privacy form generator

- terraform/privacy-statements.alpha.canada.ca.tf
URLs were working but SSL cert was not.
> use cname from Heroku to fix SSL

- terraform/notification.alpha.canada.ca.tf
Change the verification strings for new landing zone
> New account verification

- terraform/notification.canada.ca-zone.tf
> notification.canada.ca

- terraform/web-templates.pspc.alpha.canada.ca.tf
> Rebase #85

- terraform/design.canada.ca.tf
> Rebase of #87

- terraform/statcan.alpha.canada.ca.tf
> Rebase of #89

- terraform/medical-devices.tbs.alpha.canada.ca.tf
- terraform/tbs.alpha.canada.ca.tf
- terraform/wayfinding.tbs.alpha.canada.ca.tf
> Rebase of 92 to delegate tbs subdomain

- terraform/cds-snc.ca.tf
Add CNAME and TXT reccord for the main assistance portal to be on Freshdesk
> Add assistance.cds-snc.ca portal

- terraform/cds-snc.ca.tf
Add the notification portal underneath the CDS support portal.
> Add notification.assistance.cds-snc.ca

- terraform/cds-snc.ca.tf
@sboisvert Is this sufficient to get you off the ground? I'm not super thrilled about the idea about extending notification.alpha.canada.ca into a third part provider (or at least, any new ones).
ref: https://github.com/cds-snc/we_are_platform/issues/31
> SPF record update to allow for freshdesk.com integration

- terraform/cds-snc.ca.tf
Add subdomain for (now bilingual) status page
> Add CNAME to status page

- terraform/pageperformance.alpha.canada.ca.tf
Rebase of https://github.com/cds-snc/dns/pull/102
> Rebase of 102

- terraform/covid-benefits.alpha.canada.ca.tf
Had to remove the CDN, sending traffic directly to app service instead.
> Updated covid-benefits origin

- terraform/statcan.alpha.canada.ca.tf
> New Domain request: statistics.alpha.canada.ca

- terraform/pulse-alpha-canada-ca.tf
- terraform/statcan.alpha.canada.ca.tf
Creating top level record for TBS OCIO Cyber, to front their tracker v2 compliance dashboard service.
> New domain: [ TBS ] pulse.alpha.canada.ca

- terraform/pageperformance.alpha.canada.ca.tf
- terraform/performance.alpha.canada.ca.tf
Submitting new request on behalf of @ryanhyma from TBS Digital Transformation Office.
> New Domain Request: performance.alpha.canada.ca 

- terraform/cds-snc.ca.tf
Creating a support portal for COVID Alert
As per request from @sagecram and @rubinahaddad, creating a CNAME to create a support portal in Freshdesk for Covid Alert
> Add covid.assistance.cds-snc.ca

- terraform/cds-snc.ca.tf
The previous CNAME was incorrect
> Move to point to Freshdesk load balancer

- terraform/tracker-alpha-canada-ca.tf
Copy of entries from #142 which is an external PR and does not run CI.
> Add entry from 142 - Add {tracker|suivi}.alpha.canada.ca

- terraform/dmarc-reports.alpha.canada.ca.tf
> feat: add DMARC report alpha domain

- terraform/notification.canada.ca-zone.tf
One last record, sorry, there are so many of them!
> feat: add SES TXT record for notification.canada.ca

- terraform/dmarc-reports.alpha.canada.ca.tf
> fix: #146 use the right zone

- terraform/notification.canada.ca-zone.tf
Did not remove SPF records on `notification.canada.ca`
> feat: set up MAIL FROM records for Notify

- terraform/platform.canad.ca.tf
Adds two new DNS zones:
```
platform.canada.ca
plateforme.canada.ca
```
> feat: Add two new DNS zones

- terraform/notification.alpha.canada.ca.tf
- terraform/notification.canada.ca-zone.tf
:warning: **DO NOT MERGE YET**
Setting up new DNS records for GC Notify preparing the production move this Sunday
> feat: set up new prod records for Notify

- terraform/notification.alpha.canada.ca.tf
- terraform/notification.canada.ca-zone.tf
We were recommended by cyber.gc.ca to switch to a stricter SPF setting when we could.
> feat: stricter SPF rules for Notify

- terraform/notification.canada.ca-zone.tf
Add a nameserver delegation for `smtp.notification.canada.ca`
> feat: add NS delegation for smtp.notification.canada.ca

- terraform/rescheduler.cds-snc.ca.tf
Adds a CNAME validation for rescheduler.cds-snc.ca ACM
> feat: validate ACM rescheduler.cds-snc.ca

- terraform/rescheduler.cds-snc.ca.tf
> feat: moving rescheduler CDN

- terraform/opencall-appelouvert-alpha-canada.ca.tf
Adds an ACM validation for new open-call site.
> feat: add open-call ACM CNAME validation

- terraform/opencall-appelouvert-alpha-canada.ca.tf
Adds the new CF distribution for open call
> feat: add new CF distribution for open call

- terraform/alpha.canada.ca-zone.tf
Updates the alpha.canada.ca cloudfront record.
> feat: update alpha.canada.ca Cloudfront

- terraform/covid-alert-portal.alpha.canada.ca.tf
Adds a small touch to investigate the state - reapplies the NS from the previous commit.
> Small touch

- terraform/forms-formulaires.alpha.canada.ca.tf
This PR adds the configuration for GCForms (forms-formulaires.alpha.canada.ca).
> GCForms DNS entry

- terraform/cse-cst.alpha.canada.ca.tf
- terraform/cyber.alpha.canada.ca.tf
Fixes https://github.com/cds-snc/dns/issues/136
Thanks @j-froy @markwooff for your patience, please never let us take that much time to handle your request next time.
> feat: delegate cse-cst and cyber.alpha.canada.ca

- terraform/cra-arc.alpha.canada.ca.tf
> Delegate cra-arc.alpha.canada.ca

- terraform/notification.canada.ca-zone.tf
Add a TXT record for Google site verification to use https://postmaster.google.com
> Google site verification for Notify

- terraform/covid-alert-portal.alpha.canada.ca.tf
Adds a verification record for the French URL
> Add verification record for covid-alert qrcode french domain

- terraform/covid-alert-portal.alpha.canada.ca.tf
Adds the other french verification record
> add verification record for portal french record

- terraform/micro-acquisition.alpha.canada.ca.tf
> Create record for micro-acquisition.alpha.canada.ca

- terraform/notification.canada.ca-zone.tf
create `api-lambda.notification.canada.ca` to hook up to the new api lambda function.
This is a suggested checklist of questions reviewers might ask during their
review | Voici une suggestion de liste de vérification comprenant des questions
que les réviseurs pourraient poser pendant leur examen :
langues officielles?
une baisse de la quantité de code couvert par les tests automatisés?
fonctionnalité existante?
que ça devrait être divisé en de plus petites demandes de tirage (« pull
requests ») afin de réduire le risque lié aux modifications?
modification de la politique de confidentialité?
préoccupations liées à la sécurité?
façon importante la performance?
risque d’utiliser des dépendances ajoutées?
setup, etc.) | Faudra-t-il mettre à jour la documentation à la suite de ce
changement …
> add record for api-lambda

- terraform/notification.canada.ca-zone.tf
We were using the wrong url for the api lambda's api gateway 🤷 
In Notify production see 
https://ca-central-1.console.aws.amazon.com/apigateway/main/publish/domain-names?domain=api-lambda.notification.canada.ca&region=ca-central-1
This is a suggested checklist of questions reviewers might ask during their
review | Voici une suggestion de liste de vérification comprenant des questions
que les réviseurs pourraient poser pendant leur examen :
langues officielles?
une baisse de la quantité de code couvert par les tests automatisés?
fonctionnalité existante?
que ça devrait être divisé en de plus petites demandes de tirage (« pull
requests ») afin de réduire le risque lié aux modifications?
modification de la politique de confidentialité?
préoccupations liées à la sécurité?
façon importante la …
> fix: prod api-lambda cname

- terraform/worksite.alpha.canada.ca.tf
Closes #206 by changing the record from an A name to a CNAME
> fix: temp adds CNAME for worksite

- terraform/worksite.alpha.canada.ca.tf
Follow up on #206 to revert CNAME to A record.
> fix: reverts to A record

- terraform/cds-snc.ca.tf
This PR adds the TXT record for Apple Business Manager to cds-snc.ca
> feat: Add apple buisness manager txt record

- terraform/tracker-alpha-canada-ca.tf
Adds a record for the log4shell tracker subdomain
> feat: tracker log4shell subdomain

- terraform/tracker-alpha-canada-ca.tf
> feat: replay of #231

- terraform/notification.canada.ca-zone.tf
Serve all Notify API traffic from the Lambda function.
> feat: Notify lambda API to 100% weight

- .github/CODEOWNERS
- .github/workflows/terraform-plan.yml
Sets the SRE teams to be Code Owners of this repo as the potential impact of something going wrong is high.
> feat: set sre teams as owners of this repo

- terraform/design.canada.ca.tf
Update design.canada.ca.tf for new documentation site for GC Design System hosted on Netlify.
> Update design.alpha.canada.ca CNAME

- terraform/design.canada.ca.tf
> Revert "Update design.alpha.canada.ca CNAME"

- terraform/statcan.alpha.canada.ca.tf
Read this PR: https://github.com/cds-snc/dns/pull/184
Recreating this so secrets are run.
> chore: update statcan cname for energy-information

- terraform/notification.alpha.canada.ca.tf
- terraform/notification.canada.ca-zone.tf
CNAME validation records for the new notify alt name
> feat: cname validation record for api notification alt name

- terraform/cds-snc.ca.tf
Adds a CNAME for support.cds-snc.ca
> Add support.cds-snc.ca

- terraform/itap-piem.alpha-canada.ca.tf
Because we stil use Github Secrets a CDS employee needs to create this
PR.
Closes https://github.com/cds-snc/dns/pull/267
> feat: adding ITAP PR Changes.

- terraform/notification.alpha.canada.ca.tf
This reverts commit a1f7b8738060ab6acaddafdbb193a4fbb7566b78.
Reinstate previous alpha API URL for Notify.
> Sequential steps (1., 2., 3., ...) that describe how to test this change. This
> will help a developer test things out without too much detective work. Also,
> include any environmental setup steps that aren't in the normal README steps
> and/or any time-based elements that this requires.
---
> Étapes consécutives (1., 2., 3., …) qui décrivent la façon de tester la
> modification. Elles aideront les développeurs à faire des tests sans avoir à
> jouer au détective. Veuillez aussi inclure toutes les étapes de configuration
> de l’environnement qui ne font pas partie des étapes normales dans le fichier
> README et tout élément temporel requis.
> Revert "Redirect api...alpha to live URL (#274)"

- .devcontainer/devcontainer.json
- .devcontainer/post-create-command.sh
- .tool-versions
Add a VS Code devcontainer with Terraform and the AWS cli installed.
> feat: add devcontainer

- terraform/statcan.alpha.canada.ca.tf
closes https://github.com/cds-snc/dns/pull/290
> fix(statcan-alpha): changes as per statscan pr

- terraform/cds-snc.ca.tf
Adds the CNAME for cloud-spend.cds-snc.ca
> Add cloud-spend.cds-snc.ca

- terraform/cpho-alpha-canada-ca.tf
- terraform/ztapattern-alpha-canada-ca.tf
Copy of #314 and #315 to enable proper CI.
> feat: add PHAC domains

- terraform/resources.alpha.canada.ca.tf
Point the Learning Resources domains to GH Pages
> Update learning resources domains

- terraform/simplify-privacy-statements.alpha.canada.ca.tf
Removed CNAME for simplify-privacy-app
> removed old domain names

- terraform/cds-snc.ca.tf
Adding new TXT record to enable Miro domain control
> feat: add TXT record for Miro domain control

- terraform/cds-snc.ca.tf
adding the dns record for Github domain verification
> feat: add cds-snc.ca domain verif challenge record

- terraform/design-system.alpha.canada.ca.tf
Updates NS records for the design system domains
> fix: update NS records for design system

- terraform/cds-snc.ca.tf
Setting up SPF/DKIM records to fix the Happy fox issue
> fix: add missing spf/dkim records

- terraform/cds-snc.ca.tf
Removing the dmarc record to fix the tf apply
> fix: remove duplicate record

- terraform/notification.canada.ca-zone.tf
Temporarily removing cname for system status
TF Apply
> removing for system status recreate

- terraform/notification.canada.ca-zone.tf
New DNS for static site
TF Apply works
> new dns for static site

- terraform/github-user.tf
Adding the permission for the GH user to create new policy version
> fix: add create policy version permission

- terraform/notification.canada.ca-role.tf
The terraform plan role needs permissions to notification.canada.ca
TF Apply works
> terraform plan permissions

- terraform/gcperformance.alpha.canada.ca.tf
Create a new NS record for the TBS GC Performance dashboard.
Point of contact is: kyle.fletcher@tbs-sct.gc.ca
- Closes #415
> feat: new gcperformance.alpha.canada.ca NS

- terraform/issue-verify.alpha.canada.ca.tf
Adding the following new domains for GC Issue and Verify:
```
issue-verify.alpha.canada.ca
deliverance-verification.alpha.canada.ca
```
> Adding new English and french domains for GC Issue and Verify prod

- terraform/issue-verify.alpha.canada.ca.tf
updated NS records for issue-verify.alpha.canada.ca
> updated NS for issue-verify.alpha.canada.ca

- terraform/cds-snc.ca.tf
Setting up the domain verification TXT record for 1Password
> feat: setup the 1Password verif txt record

- .github/CODEOWNERS
Replace the old team name with myself.
> chore: update CODEOWNERS to include @patheard

- README.md
Updating contact email address
> Fix: update contact email address

- terraform/sds.alpha.canada.ca.tf
- Science data solutions / Solutions de données scientifiques (SDS)
- Contact email address [datasolutions-solutiondedonnees@ssc-spc.gc.ca](mailto:datasolutions-solutiondedonnees@ssc-spc.gc.ca)
- Closes #471
> feat: add subdomain delegation for sds.alpha.canada.ca

- terraform/sds.alpha.canada.ca.tf
Update with the new name servers.
- Closes https://github.com/cds-snc/dns/issues/471
> fix: update SDS subdomain delegation NS records

- terraform/ai-answers.alpha.canada.ca.tf
Replicate PR #487 for workflows to run
> fix: change reponses-ia.alpha.canada.ca record type from CNAME to NS 
